#!/bin/bash

set -e

list="$@"
if [[ -z $list ]]
then
    list=$(ls -1 test.otto.1* | sort -r)
fi

for file in test.otto $list
do
    if [[ ! -s $file ]]
    then
        continue
    fi
    echo $file
    ./digest < $file | ./digest2report
    echo "---"

done
